### ISSUE TITLE
请问您的数据构建后是如何构建可视化图谱的？谢谢

### ISSUE THREAD

**Issue by LiQiuAo** [SeanLee97/TripleIE#2]
rt

**Comment by SeanLee97** [comment]
flask + d3.js 实现的可视化，可视化不属于本 repo 的范围，有个类似的可视化方案，可以 star 一下：https://github.com/liuyuzhangolvz/novel-kg#%E5%9B%BE%E8%B0%B1%E9%97%AE%E7%AD%94%E7%B3%BB%E7%BB%9F

**Comment by LiQiuAo** [comment]
> flask + d3.js 实现的可视化，可视化不属于本 repo 的范围，有个类似的可视化方案，可以 star 一下：https://github.com/liuyuzhangolvz/novel-kg#%E5%9B%BE%E8%B0%B1%E9%97%AE%E7%AD%94%E7%B3%BB%E7%BB%9F
没能及时回复，非常感谢！！！
